<html>
<head>
<title>Error Handling in Node.js</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Node.js中的错误处理</h1>
<blockquote>原文：<a href="https://medium.com/geekculture/error-handling-in-node-js-9ae692f1ae1?source=collection_archive---------11-----------------------#2021-11-08">https://medium.com/geekculture/error-handling-in-node-js-9ae692f1ae1?source=collection_archive---------11-----------------------#2021-11-08</a></blockquote><div><div class="ds gw gx gy gz ha"/><div class="hb hc hd he hf"><div class=""/><p id="4aa4" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">遇到错误的方法有很多，要克服它们并不容易。当我们制作我们的项目时，我们想知道它已经被处理好了，并且针对可能出现的任何混乱进行了整合。</p><figure class="je jf jg jh fd ji er es paragraph-image"><div role="button" tabindex="0" class="jj jk di jl bf jm"><div class="er es jd"><img src="../Images/09cb216e99b6030b2722ce4abcb305fb.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*2ECftxbfjMRBo4ou240e0A.jpeg"/></div></div></figure><p id="9784" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">让我们考虑一个场景，我们用Node.js 构建一个<strong class="ih hj"> RESTful web API。我们有许多用户从我们的服务器发送数据请求。听起来不错。暂时如此。</strong></p><p id="f59c" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">随着来自世界各地的人们向我们的服务器发出请求，我们很有可能将一些<strong class="ih hj">意想不到的价值</strong>带入我们的程序。一旦我们有了这些值，我们想给我们的用户一个尽可能描述性的答案。如果我们没有适当的Node.js错误处理，我们很可能会抛出一个简单的错误消息。用户很可能会看到<strong class="ih hj">【出了点问题】</strong>消息。</p><figure class="je jf jg jh fd ji er es paragraph-image"><div role="button" tabindex="0" class="jj jk di jl bf jm"><div class="er es jp"><img src="../Images/bebee58340152a093e37565b66323206.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*tLm32WzQxwYpDqJZ"/></div></div><figcaption class="jq jr et er es js jt bd b be z dx">Photo by <a class="ae ju" href="https://unsplash.com/@elisa_ventur?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Elisa Ventur</a> on <a class="ae ju" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></figcaption></figure><h2 id="cd8a" class="jv jw hi bd jx jy jz ka kb kc kd ke kf iq kg kh ki iu kj kk kl iy km kn ko kp bi translated">这不是一个好的做法。</h2><p id="9cf8" class="pw-post-body-paragraph if ig hi ih b ii kq ik il im kr io ip iq ks is it iu kt iw ix iy ku ja jb jc hb bi translated">为了很好地理解错误处理概念，首先需要理解错误对象。</p><pre class="je jf jg jh fd kv kw kx ky aw kz bi"><span id="1958" class="jv jw hi kw b fi la lb l lc ld">throw new Error('database failed to connect');</span></pre><p id="45c4" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">本机错误对象的第一个参数是它的描述。描述是错误对象的可读字符串。当有什么出错的时候，它就会出现在你的控制台上。</p><pre class="je jf jg jh fd kv kw kx ky aw kz bi"><span id="f8c7" class="jv jw hi kw b fi la lb l lc ld">throw new CustomError('A custom error');</span></pre><p id="73dd" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">第二个错误对象也有一个name属性，它是对象的计算机可读部分。当使用本机错误对象时，name属性默认为一般的“错误”，但您可以创建自己的。</p><p id="bcb9" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">创建一个错误对象并不是我们的目的。创建一个错误对象只是隐喻性地为发送错误做准备，但它并不发送。要发送我们的错误，我们需要抛出它。但是扔是什么意思呢？这对我们的项目意味着什么？</p><p id="fb3e" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">Throw实际上做了两件事:它停止程序，并找到一个要执行的catch。</p><p id="7b41" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">当JavaScript找到throw关键字时，它做的第一件事就是立即停止，这阻止了更多函数的运行。通过像这样停止，它减少了任何进一步错误发生的风险，并帮助我们不使我们的程序状态完全扭曲。</p><figure class="je jf jg jh fd ji er es paragraph-image"><div role="button" tabindex="0" class="jj jk di jl bf jm"><div class="er es le"><img src="../Images/c4455161ddf5ba53cb3b6650b8a5a4a5.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*jqYGy5JOYpbcC9C3"/></div></div><figcaption class="jq jr et er es js jt bd b be z dx">Photo by <a class="ae ju" href="https://unsplash.com/@flowforfrank?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Ferenc Almasi</a> on <a class="ae ju" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></figcaption></figure><h2 id="866e" class="jv jw hi bd jx jy jz ka kb kc kd ke kf iq kg kh ki iu kj kk kl iy km kn ko kp bi translated">处理异步错误</h2><p id="4816" class="pw-post-body-paragraph if ig hi ih b ii kq ik il im kr io ip iq ks is it iu kt iw ix iy ku ja jb jc hb bi translated">在我们深入之前，让我们后退一步，理解JavaScript如何处理异步任务——以及我们为什么需要这样做。</p><p id="c0f7" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">JavaScript是一种单线程编程语言。由于只有一个处理器，我们得到了阻塞代码。阻塞代码指的是你的程序是否会等待一个异步任务完成后再做其他事情，而非阻塞代码指的是当任务完成时你在哪里注册一个回调函数来执行。</p><p id="c8c0" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">在这一点上，值得一提的是，在JavaScript中有两种处理异步的主要方法:承诺或回调。</p><p id="9881" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">Promises非常优雅地处理错误，并将捕获链中在它之前的任何错误，这对于Node.js程序员来说非常好，因为这意味着我们可以在单个处理程序中处理许多函数中的许多错误。</p><p id="333f" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">在这一点上，你可能想知道给你的承诺增加一个条件是否是可选的。这是可选的，但是你应该总是提供一个catch处理程序。</p><p id="c63d" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">因为异步调用失败的方式有很多。我们的代码可能超时，可能有网络问题，或者可能有硬件故障。出于所有这些原因，您应该始终指导您的程序在承诺失败的情况下做什么。</p><p id="f32a" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">记住黄金法则:<strong class="ih hj">永远要处理承诺的拒绝。</strong></p><figure class="je jf jg jh fd ji er es paragraph-image"><div role="button" tabindex="0" class="jj jk di jl bf jm"><div class="er es lf"><img src="../Images/c934fc815eba4453e5ea9b25fbe91bae.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*MGdn-1cED2gchx7Y"/></div></div><figcaption class="jq jr et er es js jt bd b be z dx">Photo by <a class="ae ju" href="https://unsplash.com/@reinf?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Raúl Nájera</a> on <a class="ae ju" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></figcaption></figure><h2 id="10c7" class="jv jw hi bd jx jy jz ka kb kc kd ke kf iq kg kh ki iu kj kk kl iy km kn ko kp bi translated">异步尝试/捕捉的危险</h2><p id="ce50" class="pw-post-body-paragraph if ig hi ih b ii kq ik il im kr io ip iq ks is it iu kt iw ix iy ku ja jb jc hb bi translated">您可能想知道为什么promise公开了一个catch方法，为什么我们不能将promise实现包装在一个try/catch中。如果你试图这样做，结果不会如你所料。</p><p id="c332" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">默认情况下Try/catch是同步的。这意味着，如果异步函数在同步try/catch块中抛出错误，则不会抛出错误。</p><p id="b0bc" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">这绝对不是我们想要的。</p><p id="fc0e" class="pw-post-body-paragraph if ig hi ih b ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc hb bi translated">总之，如果您正在处理异步错误处理，您应该真正使用promises catch处理程序，因为这将允许您有效地处理异步错误。但是如果您处理的是同步代码，那么try/catch会做得很好。</p></div></div>    
</body>
</html>